#!/usr/bin/env bash
#
# Basic symlinks
#
# ============================================================================
# Initialize script
# ============================================================================

if [[ -z "$DOTFILES_DIRECTORY" ]]; then
  cd -- "$(dirname "$0")/.." || exit 1
  DOTFILES_DIRECTORY="$PWD"
fi

# ============================================================================
# Main
# ============================================================================

__symlink() {
  ln -s "${DOTFILES_DIRECTORY}/zsh/.zshrc" "${HOME}/.zshrc"
  ln -s "${DOTFILES_DIRECTORY}/git/.gitconfig" "${HOME}/.gitconfig"
}

__symlink