#!/usr/bin/env bash
#
# Basic symlinks
#
# ============================================================================
# Initialize script
# ============================================================================

if [[ -z "$DOTFILES_DIRECTORY" ]]; then
  cd -- "$(dirname "$0")/.." || exit 1
  DOTFILES_DIRECTORY="$PWD"
fi

# ============================================================================
# Main
# ============================================================================

__symlink() {
  ln -s "${DOTFILES_DIRECTORY}/zsh/.zshrc" "${HOME}/.zshrc"
  ln -s "${DOTFILES_DIRECTORY}/git/.gitconfig" "${HOME}/.gitconfig"

  # Visual studio code settings
  ln -s "${DOTFILES_DIRECTORY}/vscode/settings.json" "${HOME}/Library/Application Support/Code/User/settings.json"
  ln -s "${DOTFILES_DIRECTORY}/vscode/keybindings.json" "${HOME}/Library/Application Support/Code/User/keybindings.json"
  ln -s "${DOTFILES_DIRECTORY}/vscode/snippets" "${HOME}/Library/Application Support/Code/User/snippets"
}

__symlink